### ISSUE TITLE
Limit number of !move commands

### ISSUE THREAD

**Issue by Gramok** [whitep4nth3r/pantherworld#91] opened 2024-08-20 11:27 UTC
Moving around the world is exhausting. You should be reminded to get some rest before you collapse.

Therefore, after a certain amount of !move commands during a defined period of time, the player must rest for a certain amount of time.

"You walked too much, get some rest!"

More items, more rest is needed.

**Comment by whitep4nth3r** [comment] 2024-08-20 11:47
Closed as duplicate of: https://github.com/whitep4nth3r/pantherworld/issues/78

**Closed by whitep4nth3r** 2024-08-20 11:47 UTC
